# Generated by Django 5.0.2 on 2024-03-04 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employeeAPI", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="worker",
                to="employeeAPI.employee",
            ),
        ),
    ]
