# Generated by Django 5.0.2 on 2024-03-04 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employeeAPI", "0002_alter_task_employee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="employee",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="worker",
                to="employeeAPI.employee",
            ),
        ),
    ]
