# Generated by Django 5.0.2 on 2024-03-04 07:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("LittlelemonAPI", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menuitem",
            name="description",
        ),
    ]
