# Generated by Django 5.0.2 on 2024-03-06 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("LittlelemonAPI", "0002_alter_category_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitem",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="LittlelemonAPI.category",
            ),
        ),
    ]
